[package]
name = "crablibs"
version = "1.1.0"
authors = ["Camden Mecklem"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
textwrap = { version = "0.14", features = ["terminal_size"] }
yansi = "0.5.0"